name: facescore_ai
description: FaceScore AI - Rate your face with AI powered analysis
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_mlkit_face_detection: ^0.10.0
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
